/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inscripciones;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author Main PC
 */
public class FrmNuevoProducto extends javax.swing.JFrame {

    /**
     * Creates new form FrmNuevoProducto
     */
    public FrmNuevoProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnOperacion1 = new javax.swing.JButton();
        cbxYear2 = new javax.swing.JComboBox<>();
        btnOperacion2 = new javax.swing.JButton();
        cbxYear3 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtDireccion3 = new javax.swing.JTextField();
        txtDireccion4 = new javax.swing.JTextField();
        txtDireccion5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 232, 232));

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setMinimumSize(new java.awt.Dimension(460, 549));
        jPanel1.setPreferredSize(new java.awt.Dimension(460, 549));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setBackground(new java.awt.Color(215, 215, 215));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(64, 64, 64));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nuevo Producto");
        jLabel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 1));
        jLabel17.setMaximumSize(new java.awt.Dimension(213, 30));
        jLabel17.setMinimumSize(new java.awt.Dimension(213, 30));
        jLabel17.setOpaque(true);
        jLabel17.setPreferredSize(new java.awt.Dimension(213, 30));
        jLabel17.setRequestFocusEnabled(false);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 400, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(64, 64, 64));
        jLabel12.setText("Nombre");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(64, 64, 64));
        jLabel13.setText("Categoria");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(64, 64, 64));
        jLabel14.setText("Marca");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(64, 64, 64));
        jLabel15.setText("Precio");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(64, 64, 64));
        jLabel16.setText("Existencias");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        btnOperacion1.setBackground(new java.awt.Color(215, 215, 215));
        btnOperacion1.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        btnOperacion1.setForeground(new java.awt.Color(64, 64, 64));
        btnOperacion1.setText("Cancelar");
        btnOperacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacion1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOperacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, 110, 30));

        cbxYear2.setBackground(new java.awt.Color(215, 215, 215));
        cbxYear2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        cbxYear2.setForeground(new java.awt.Color(64, 64, 64));
        cbxYear2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        cbxYear2.setBorder(null);
        cbxYear2.setOpaque(true);
        cbxYear2.setPreferredSize(new java.awt.Dimension(72, 25));
        jPanel1.add(cbxYear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 270, -1));

        btnOperacion2.setBackground(new java.awt.Color(2, 62, 138));
        btnOperacion2.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 18)); // NOI18N
        btnOperacion2.setForeground(new java.awt.Color(232, 232, 232));
        btnOperacion2.setText("Finalizar");
        btnOperacion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperacion2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnOperacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 110, 30));

        cbxYear3.setBackground(new java.awt.Color(215, 215, 215));
        cbxYear3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        cbxYear3.setForeground(new java.awt.Color(64, 64, 64));
        cbxYear3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018" }));
        cbxYear3.setBorder(null);
        cbxYear3.setOpaque(true);
        cbxYear3.setPreferredSize(new java.awt.Dimension(72, 25));
        jPanel1.add(cbxYear3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 270, -1));

        jCheckBox1.setBackground(new java.awt.Color(232, 232, 232));
        jCheckBox1.setSelected(true);
        jCheckBox1.setBorder(null);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 20, 25));

        txtDireccion3.setBackground(new java.awt.Color(215, 215, 215));
        txtDireccion3.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        txtDireccion3.setBorder(null);
        txtDireccion3.setFocusable(false);
        txtDireccion3.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDireccion3.setSelectionColor(new java.awt.Color(0, 102, 153));
        jPanel1.add(txtDireccion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 240, -1));

        txtDireccion4.setBackground(new java.awt.Color(215, 215, 215));
        txtDireccion4.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        txtDireccion4.setBorder(null);
        txtDireccion4.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDireccion4.setSelectionColor(new java.awt.Color(0, 102, 153));
        jPanel1.add(txtDireccion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 270, -1));

        txtDireccion5.setBackground(new java.awt.Color(215, 215, 215));
        txtDireccion5.setFont(new java.awt.Font("Malgun Gothic Semilight", 0, 14)); // NOI18N
        txtDireccion5.setBorder(null);
        txtDireccion5.setPreferredSize(new java.awt.Dimension(64, 25));
        txtDireccion5.setSelectionColor(new java.awt.Color(0, 102, 153));
        jPanel1.add(txtDireccion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOperacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOperacion1ActionPerformed

    private void btnOperacion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperacion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOperacion2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                new FrmNuevoProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnOperacion1;
    public static javax.swing.JButton btnOperacion2;
    private static javax.swing.JComboBox<String> cbxYear2;
    private static javax.swing.JComboBox<String> cbxYear3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField txtDireccion3;
    private static javax.swing.JTextField txtDireccion4;
    private static javax.swing.JTextField txtDireccion5;
    // End of variables declaration//GEN-END:variables
}
