/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Inscripciones;


import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.Statement;

/**
 *
 * @author Kevin MG
 */
public class PnlProveedores extends javax.swing.JPanel {

    /**
     * Creates new form pnlFinanzas
     */
    public PnlProveedores() {
        initComponents();
    }

    static String sql;
    static Conectar con = new Conectar();
    static PreparedStatement ps;
    static Statement sentencia;
    static ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnVerEmpleados1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(232, 232, 232));
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        setPreferredSize(new java.awt.Dimension(1200, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Buscar");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 35, 70, -1));

        btnVerEmpleados1.setBackground(new java.awt.Color(2, 62, 138));
        btnVerEmpleados1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerEmpleados1.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEmpleados1.setText("Nuevo");
        btnVerEmpleados1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVerEmpleados1.setFocusPainted(false);
        btnVerEmpleados1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerEmpleados1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerEmpleados1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEmpleados1ActionPerformed(evt);
            }
        });
        add(btnVerEmpleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, 110, 40));

        jTextField1.setBackground(new java.awt.Color(215, 215, 215));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(142, 142, 142));
        jTextField1.setText("ID del Proveedor...");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 16, 1, 1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 270, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nuestros proveedores");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, -1));

        jScrollPane1.setBackground(new java.awt.Color(232, 232, 232));

        jList1.setBackground(new java.awt.Color(232, 232, 232));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1140, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerEmpleados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEmpleados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerEmpleados1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerEmpleados1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
