/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inscripciones;

import static Inscripciones.pnlNuevaInscripcion.desbloquearEdicion;
import com.itextpdf.text.Chunk;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
//import javax.swing.text.Document;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JComboBox;

/**
 *
 * @author Kevin MG
 */
public class Principal extends javax.swing.JFrame implements FocusListener {

    public Principal() {
        initComponents();
        btnEmpleados.addMouseListener(ml);
        btnEmpleados.addFocusListener(this);

        btnProductos.addMouseListener(ml);
        btnProductos.addFocusListener(this);

        btnProveedores.addMouseListener(ml);
        btnProveedores.addFocusListener(this);
        
        btnEntregas.addMouseListener(ml);
        btnEntregas.addFocusListener(this);

        btnVentas.addMouseListener(ml);
        btnVentas.addFocusListener(this);
        
        btnSalir.addMouseListener(ml);
        btnSalir.addFocusListener(this);

        getContentPane().removeAll();

        pnlIzquierdo.setLayout(new BoxLayout(pnlIzquierdo, BoxLayout.PAGE_AXIS));
        pnlIzquierdo.add(pnlMenu);
        add(pnlIzquierdo);

        pnlDerecho.setLayout(new BoxLayout(pnlDerecho, BoxLayout.PAGE_AXIS));
        pnlDerecho.add(pnlPrincipal);
        add(pnlDerecho);

        revalidate();
        repaint();
    }

    static JPanel pnlDerecho = new JPanel();
    static JPanel pnlIzquierdo = new JPanel();

    static String sql;
    static Conectar con = new Conectar();
    static Connection reg = con.conexion();
    static PreparedStatement ps;
    static Statement sentencia;
    static ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEntregas = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnInsertarEmpleado = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnEditarEmpleados = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        showTurno = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        showID = new javax.swing.JButton();
        showNombre = new javax.swing.JButton();
        showPuesto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lblEmpleado6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnBajas1 = new javax.swing.JButton();
        btnVerEmpleados = new javax.swing.JButton();
        btnEliminarEmpleados = new javax.swing.JButton();
        lblEmpleado1 = new javax.swing.JLabel();
        lblEmpleado2 = new javax.swing.JLabel();
        lblEmpleado3 = new javax.swing.JLabel();
        lblEmpleado4 = new javax.swing.JLabel();
        lblEmpleado5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(187, 187, 187));
        setMinimumSize(new java.awt.Dimension(1400, 781));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1410, 781));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlMenu.setBackground(new java.awt.Color(2, 62, 138));
        pnlMenu.setMaximumSize(new java.awt.Dimension(210, 781));
        pnlMenu.setMinimumSize(new java.awt.Dimension(210, 781));
        pnlMenu.setPreferredSize(new java.awt.Dimension(210, 780));
        pnlMenu.setRequestFocusEnabled(false);
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpleados.setBackground(new java.awt.Color(2, 62, 138));
        btnEmpleados.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(232, 230, 230));
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoInscribir.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setAlignmentY(0.0F);
        btnEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEmpleados.setFocusPainted(false);
        btnEmpleados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEmpleados.setIconTextGap(15);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 80));

        btnProductos.setBackground(new java.awt.Color(2, 62, 138));
        btnProductos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(232, 230, 230));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoPanelGrupos.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProductos.setFocusPainted(false);
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.setIconTextGap(15);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        pnlMenu.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 80));

        btnProveedores.setBackground(new java.awt.Color(2, 62, 138));
        btnProveedores.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(232, 230, 230));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzas.png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnProveedores.setFocusPainted(false);
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedores.setIconTextGap(15);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        pnlMenu.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 80));

        btnSalir.setBackground(new java.awt.Color(2, 62, 138));
        btnSalir.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(232, 230, 230));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoSalir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setIconTextGap(15);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 210, 80));

        btnEntregas.setBackground(new java.awt.Color(2, 62, 138));
        btnEntregas.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnEntregas.setForeground(new java.awt.Color(232, 230, 230));
        btnEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzas.png"))); // NOI18N
        btnEntregas.setText("Entregas");
        btnEntregas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEntregas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEntregas.setFocusPainted(false);
        btnEntregas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEntregas.setIconTextGap(15);
        btnEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 210, 80));

        btnVentas.setBackground(new java.awt.Color(2, 62, 138));
        btnVentas.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(232, 230, 230));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzas.png"))); // NOI18N
        btnVentas.setText("Ventas");
        btnVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVentas.setFocusPainted(false);
        btnVentas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVentas.setIconTextGap(15);
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 210, 80));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ferreteria");
        pnlMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        getContentPane().add(pnlMenu);

        pnlPrincipal.setBackground(new java.awt.Color(232, 232, 232));
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(1200, 780));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(1200, 780));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1200, 780));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Turno");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 50, -1));

        btnInsertarEmpleado.setBackground(new java.awt.Color(1, 50, 112));
        btnInsertarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnInsertarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarEmpleado.setText("Nuevo Trabajador");
        btnInsertarEmpleado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnInsertarEmpleado.setFocusPainted(false);
        btnInsertarEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInsertarEmpleado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnInsertarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarEmpleadoActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnInsertarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 570, 240, 35));

        jButton4.setBackground(new java.awt.Color(215, 215, 215));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(64, 64, 64));
        jButton4.setText("Herramientas del Gerente");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        pnlPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 515, 390, 33));

        jButton5.setBackground(new java.awt.Color(215, 215, 215));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(64, 64, 64));
        jButton5.setText("Acciones del Perfil");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);
        pnlPrincipal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 650, 33));

        btnEditarEmpleados.setBackground(new java.awt.Color(1, 50, 112));
        btnEditarEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarEmpleados.setText("Modificar empleados");
        btnEditarEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEditarEmpleados.setFocusPainted(false);
        btnEditarEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditarEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEmpleadosActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnEditarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 630, 240, 35));

        btnModificar.setBackground(new java.awt.Color(2, 62, 138));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoEditar.png"))); // NOI18N
        btnModificar.setText("Modificar Datos");
        btnModificar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnModificar.setFocusPainted(false);
        btnModificar.setIconTextGap(8);
        btnModificar.setPreferredSize(new java.awt.Dimension(75, 27));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 290, 50));

        btnPDF.setBackground(new java.awt.Color(2, 62, 138));
        btnPDF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoPDF.png"))); // NOI18N
        btnPDF.setText("Imprimir Datos del Empleado");
        btnPDF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPDF.setBorderPainted(false);
        btnPDF.setFocusPainted(false);
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 290, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fecha");
        pnlPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");
        pnlPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 70, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1085, 150, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Herramientas.png"))); // NOI18N
        pnlPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 570, 100, -1));

        showTurno.setBackground(new java.awt.Color(215, 215, 215));
        showTurno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showTurno.setForeground(new java.awt.Color(102, 102, 102));
        showTurno.setText("Turno");
        showTurno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 1));
        showTurno.setBorderPainted(false);
        showTurno.setFocusPainted(false);
        showTurno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showTurno.setMargin(new java.awt.Insets(8, 14, 2, 14));
        pnlPrincipal.add(showTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 495, 40));

        jButton7.setBackground(new java.awt.Color(215, 215, 215));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jButton7.setForeground(new java.awt.Color(64, 64, 64));
        jButton7.setText("Familia Ferreteria");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setBorderPainted(false);
        jButton7.setFocusPainted(false);
        pnlPrincipal.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 400, 33));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Puesto");
        pnlPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 50, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/sol.png"))); // NOI18N
        pnlPrincipal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 425, 30, -1));

        jButton8.setBackground(new java.awt.Color(215, 215, 215));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jButton8.setForeground(new java.awt.Color(64, 64, 64));
        jButton8.setText("Datos del Perfil");
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton8.setBorderPainted(false);
        jButton8.setFocusPainted(false);
        pnlPrincipal.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 650, 33));

        showID.setBackground(new java.awt.Color(215, 215, 215));
        showID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showID.setForeground(new java.awt.Color(102, 102, 102));
        showID.setText("Datos del Perfil");
        showID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 1));
        showID.setBorderPainted(false);
        showID.setFocusPainted(false);
        showID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showID.setMargin(new java.awt.Insets(8, 14, 2, 14));
        pnlPrincipal.add(showID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 350, 40));

        showNombre.setBackground(new java.awt.Color(215, 215, 215));
        showNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showNombre.setForeground(new java.awt.Color(102, 102, 102));
        showNombre.setText("Nombre");
        showNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 1));
        showNombre.setBorderPainted(false);
        showNombre.setFocusPainted(false);
        showNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showNombre.setMargin(new java.awt.Insets(8, 14, 2, 14));
        pnlPrincipal.add(showNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 495, 40));

        showPuesto.setBackground(new java.awt.Color(215, 215, 215));
        showPuesto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showPuesto.setForeground(new java.awt.Color(102, 102, 102));
        showPuesto.setText("Puesto");
        showPuesto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 1));
        showPuesto.setBorderPainted(false);
        showPuesto.setFocusPainted(false);
        showPuesto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showPuesto.setMargin(new java.awt.Insets(8, 14, 2, 14));
        pnlPrincipal.add(showPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 350, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar (1).png"))); // NOI18N
        pnlPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 185, 30, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/id-insignia.png"))); // NOI18N
        pnlPrincipal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 265, 30, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/maletin.png"))); // NOI18N
        pnlPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 345, 30, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/retrato (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 130, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 70, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("ID");
        pnlPrincipal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 20, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 70, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 150, 70, -1));

        lblEmpleado6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpleado6.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado6.setText("Empleado 1");
        pnlPrincipal.add(lblEmpleado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 400, 90, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 310, 70, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1085, 310, 70, -1));

        btnBajas1.setBackground(new java.awt.Color(1, 50, 112));
        btnBajas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBajas1.setForeground(new java.awt.Color(255, 255, 255));
        btnBajas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoEliminar.png"))); // NOI18N
        btnBajas1.setText("Darse de baja");
        btnBajas1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBajas1.setFocusPainted(false);
        btnBajas1.setIconTextGap(8);
        btnBajas1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBajas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajas1ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnBajas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 280, 50));

        btnVerEmpleados.setBackground(new java.awt.Color(2, 62, 138));
        btnVerEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEmpleados.setText("Ver todos");
        btnVerEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnVerEmpleados.setFocusPainted(false);
        btnVerEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEmpleadosActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnVerEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 390, 30));

        btnEliminarEmpleados.setBackground(new java.awt.Color(1, 50, 112));
        btnEliminarEmpleados.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpleados.setText("Dar de baja empleados");
        btnEliminarEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEliminarEmpleados.setFocusPainted(false);
        btnEliminarEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEmpleadosActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnEliminarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 690, 390, 35));

        lblEmpleado1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpleado1.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado1.setText("Empleado 1");
        pnlPrincipal.add(lblEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 90, -1));

        lblEmpleado2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpleado2.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado2.setText("Empleado 1");
        pnlPrincipal.add(lblEmpleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 90, -1));

        lblEmpleado3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpleado3.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado3.setText("Empleado 1");
        pnlPrincipal.add(lblEmpleado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 230, 90, -1));

        lblEmpleado4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpleado4.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado4.setText("Empleado 1");
        pnlPrincipal.add(lblEmpleado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 90, -1));

        lblEmpleado5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmpleado5.setForeground(new java.awt.Color(0, 0, 0));
        lblEmpleado5.setText("Empleado 1");
        pnlPrincipal.add(lblEmpleado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 400, 90, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, 640));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Bienvenido NOMBRE");
        pnlPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 230, -1));

        getContentPane().add(pnlPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int salir = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres salir?", "Salir", JOptionPane.YES_OPTION);
        if (salir == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        pnlResultadoBusqueda.cima1 = 0;
        pnlDerecho.removeAll();
        pnlDerecho.add(pnlPrincipal);
        pnlNuevaInscripcion.btnOperacion.show();
        revalidate();
        repaint();
        desbloquearEdicion();
    }//GEN-LAST:event_btnEmpleadosActionPerformed
    JPanel pnlFinanzas = new pnlFinanzas();
    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        pnlDerecho.removeAll();
        pnlDerecho.add(pnlFinanzas);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnProveedoresActionPerformed
    static String operacion;
    static String taller;
    static JPanel pnlInscribir = new pnlNuevaInscripcion();    static pnlResultadoBusqueda pnlBusqueda = new pnlResultadoBusqueda();
    private void btnEditarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEmpleadosActionPerformed
        pnlResultadoBusqueda.buscarContacto("Mostrar", true, 0);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnEditarEmpleadosActionPerformed
    JPanel pnlGrupos = new pnlGrupos();
    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        pnlDerecho.removeAll();
        pnlDerecho.add(pnlGrupos);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        Document documento = new Document(PageSize.A4.rotate());

        JComboBox cbxTablas = new JComboBox();
        cbxTablas.addItem("General");
        cbxTablas.addItem("Primaria");
        cbxTablas.addItem("Secundaria");
        cbxTablas.addItem("Preparatoria");

        Object[] inputFields = {"Seleccione la lista a imprimir:\n", cbxTablas};

        JOptionPane.showConfirmDialog(null, inputFields, "Seleccionar Tabla", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        sql = "SELECT matricula, nombre, apaterno, amaterno, nivel, grado, turno, year, calificacion FROM alumnos";
        switch (cbxTablas.getSelectedItem().toString()) {
            case "General":
                break;
            case "Primaria":
                sql += " WHERE nivel = 'Primaria'";
                break;
            case "Secundaria":
                sql += " WHERE nivel = 'Secundaria'";
                break;
            case "Preparatoria":
                sql += " WHERE nivel = 'Preparatoria'";
                break;
            default:
                break;
        }

        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte_Inscripciones.pdf"));
            documento.open();
            //Ajustar Fuente
            Font fuente = new Font();
            fuente.setStyle(Font.BOLD);
            fuente.setSize(16);
            //Agregar Titulo
            Paragraph parrafo = new Paragraph("INSTITUTO TECNOLÓGICO ASCENSIÓN", fuente);
            parrafo.setAlignment(Element.ALIGN_CENTER);
            documento.add(parrafo);
            documento.add(Chunk.NEWLINE);
            //Agregar informacion
            documento.add(new Paragraph("Tabla de Alumnos: " + cbxTablas.getSelectedItem().toString()));
            documento.add(new Paragraph("Reporte generado por usuario: Admin\n"));
            documento.add(Chunk.NEWLINE);
            //Crear tabla
            PdfPTable tabla = new PdfPTable(9);
            tabla.setWidthPercentage(100);
            //Ajustar anchura de columnas
            float[] columnWidths = {1.1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f};
            tabla.setWidths(columnWidths);
            //Ajustar fuente
            fuente = new Font();
            fuente.setStyle(Font.BOLD);
            //Agregar encabezados de tabls
            PdfPCell c1 = new PdfPCell(new Phrase("Matricula", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Nombre", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Ap Paterno", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Ap Materno", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Nivel", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Grado", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Turno", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Año Nac.", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Calificacion", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            try {
                sentencia = reg.createStatement();
                rs = sentencia.executeQuery(sql);

                if (rs.next()) {
                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        tabla.addCell(rs.getString(6));
                        tabla.addCell(rs.getString(7));
                        tabla.addCell(rs.getString(8));
                        tabla.addCell(rs.getString(9));

                    } while (rs.next());
                    documento.add(tabla);
                }

            } catch (DocumentException | SQLException e) {
            }
            documento.close();

            if (JOptionPane.showConfirmDialog(null, "Reporte guardado en el escritorio\n¿Desea abrirlo?", "Abrir Documento", JOptionPane.YES_OPTION) == 0) {
                try {
                    File path = new File(ruta + "/Desktop/Reporte_Inscripciones.pdf");
                    Desktop.getDesktop().open(path);
                } catch (IOException | java.lang.IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(null, "No se pudo abrir el archivo. Es posible que este haya sido eliminado o movido del escritorio", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntregasActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnInsertarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarEmpleadoActionPerformed
        operacion = "Preparatoria";
        pnlNuevaInscripcion.llenarGrado();
        pnlDerecho.remove(pnlPrincipal);
        pnlDerecho.add(pnlInscribir);
        revalidate();
        repaint();
        pnlNuevaInscripcion.btnTitulo.setText("Inscripción a Preparatoria");
    }//GEN-LAST:event_btnInsertarEmpleadoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        pnlResultadoBusqueda.buscarContacto("Modificar", true, 0);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBajas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajas1ActionPerformed

    private void btnVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerEmpleadosActionPerformed

    private void btnEliminarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarEmpleadosActionPerformed

    public static void cargarInicio() {
        pnlDerecho.removeAll();
        pnlDerecho.add(pnlPrincipal);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Principal().setVisible(true);
            }
        });
    }

    @Override
    public void focusGained(FocusEvent evt) {
        Component c = evt.getComponent();
        if (c == btnEmpleados) {
            btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoInscribirActivado.png")));
            btnEmpleados.setBackground(new Color(1, 49, 109));
        } else if (c == btnProductos) {
            btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoPanelGruposActivado.png")));
            btnProductos.setBackground(new Color(1, 49, 109));
        } else if (c == btnProveedores) {
            btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzasActivado.png")));
            btnProveedores.setBackground(new Color(1, 49, 109));
        } else if (c == btnSalir) {
            btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoSalirActivado.png")));
            btnSalir.setBackground(new Color(1, 49, 109));
        }
    }

    @Override
    public void focusLost(FocusEvent evt) {
        Component c = evt.getComponent();
        if (c == btnEmpleados) {
            btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoInscribir.png")));
            btnEmpleados.setBackground(new Color(2, 62, 138));
        } else if (c == btnProductos) {
            btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoPanelGrupos.png")));
            btnProductos.setBackground(new Color(2, 62, 138));
        } else if (c == btnProveedores) {
            btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzas.png")));
            btnProveedores.setBackground(new Color(2, 62, 138));
        } else if (c == btnSalir) {
            btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoSalir.png")));
            btnSalir.setBackground(new Color(2, 62, 138));
        }
    }

    MouseListener ml = new MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            Component c = evt.getComponent();
            c.setBackground(new Color(1, 49, 109));
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            Component c = evt.getComponent();
            if (!c.hasFocus()) {
                c.setBackground(new Color(2, 62, 138));
            }
        }

        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            Component c = evt.getComponent();
            c.setBackground(new Color(1, 49, 109));
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajas1;
    private javax.swing.JButton btnEditarEmpleados;
    private javax.swing.JButton btnEliminarEmpleados;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEntregas;
    private javax.swing.JButton btnInsertarEmpleado;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVerEmpleados;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEmpleado1;
    private javax.swing.JLabel lblEmpleado2;
    private javax.swing.JLabel lblEmpleado3;
    private javax.swing.JLabel lblEmpleado4;
    private javax.swing.JLabel lblEmpleado5;
    private javax.swing.JLabel lblEmpleado6;
    private javax.swing.JPanel pnlMenu;
    public static javax.swing.JPanel pnlPrincipal;
    private javax.swing.JButton showID;
    private javax.swing.JButton showNombre;
    private javax.swing.JButton showPuesto;
    private javax.swing.JButton showTurno;
    // End of variables declaration//GEN-END:variables
}
