/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Inscripciones;

import static Inscripciones.pnlNuevaInscripcion.desbloquearEdicion;
import com.itextpdf.text.Chunk;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
//import javax.swing.text.Document;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JComboBox;

/**
 *
 * @author Kevin MG
 */
public class Principal extends javax.swing.JFrame implements FocusListener {

    public Principal() {
        initComponents();
        btnInscripciones.addMouseListener(ml);
        btnInscripciones.addFocusListener(this);

        /*btnBecas.addMouseListener(ml);
        btnBecas.addFocusListener(this);*/
        btnGrupos.addMouseListener(ml);
        btnGrupos.addFocusListener(this);

        btnFinanzas.addMouseListener(ml);
        btnFinanzas.addFocusListener(this);

        btnSalir.addMouseListener(ml);
        btnSalir.addFocusListener(this);

        getContentPane().removeAll();

        pnlIzquierdo.setLayout(new BoxLayout(pnlIzquierdo, BoxLayout.PAGE_AXIS));
        pnlIzquierdo.add(pnlMenu);
        add(pnlIzquierdo);

        pnlDerecho.setLayout(new BoxLayout(pnlDerecho, BoxLayout.PAGE_AXIS));
        pnlDerecho.add(pnlTitulo);
        pnlDerecho.add(pnlPrincipal);
        add(pnlDerecho);

        revalidate();
        repaint();
    }

    static JPanel pnlDerecho = new JPanel();
    static JPanel pnlIzquierdo = new JPanel();

    static String sql;
    static Conectar con = new Conectar();
    static Connection reg = con.conexion();
    static PreparedStatement ps;
    static Statement sentencia;
    static ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        btnInscripciones = new javax.swing.JButton();
        btnGrupos = new javax.swing.JButton();
        btnFinanzas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnFinanzas1 = new javax.swing.JButton();
        btnFinanzas2 = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnPrepa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnConsultaAlumnos = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        showTurno = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        showID = new javax.swing.JButton();
        showNombre = new javax.swing.JButton();
        showPuesto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnBajas1 = new javax.swing.JButton();
        btnConsultaAlumnos1 = new javax.swing.JButton();
        btnConsultaAlumnos2 = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblEscuela = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(2, 62, 138));
        setMinimumSize(new java.awt.Dimension(1400, 781));
        setPreferredSize(new java.awt.Dimension(1400, 781));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnlMenu.setBackground(new java.awt.Color(2, 62, 138));
        pnlMenu.setMaximumSize(new java.awt.Dimension(210, 781));
        pnlMenu.setMinimumSize(new java.awt.Dimension(210, 781));
        pnlMenu.setPreferredSize(new java.awt.Dimension(210, 781));
        pnlMenu.setRequestFocusEnabled(false);
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInscripciones.setBackground(new java.awt.Color(2, 62, 138));
        btnInscripciones.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnInscripciones.setForeground(new java.awt.Color(232, 230, 230));
        btnInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoInscribir.png"))); // NOI18N
        btnInscripciones.setText("Empleados");
        btnInscripciones.setAlignmentY(0.0F);
        btnInscripciones.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnInscripciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInscripciones.setFocusPainted(false);
        btnInscripciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInscripciones.setIconTextGap(15);
        btnInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionesActionPerformed(evt);
            }
        });
        pnlMenu.add(btnInscripciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 210, 80));

        btnGrupos.setBackground(new java.awt.Color(2, 62, 138));
        btnGrupos.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnGrupos.setForeground(new java.awt.Color(232, 230, 230));
        btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoPanelGrupos.png"))); // NOI18N
        btnGrupos.setText("Productos");
        btnGrupos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGrupos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGrupos.setFocusPainted(false);
        btnGrupos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGrupos.setIconTextGap(15);
        btnGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGruposActionPerformed(evt);
            }
        });
        pnlMenu.add(btnGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 210, 80));

        btnFinanzas.setBackground(new java.awt.Color(2, 62, 138));
        btnFinanzas.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnFinanzas.setForeground(new java.awt.Color(232, 230, 230));
        btnFinanzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzas.png"))); // NOI18N
        btnFinanzas.setText("Proveedores");
        btnFinanzas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFinanzas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFinanzas.setFocusPainted(false);
        btnFinanzas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanzas.setIconTextGap(15);
        btnFinanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanzasActionPerformed(evt);
            }
        });
        pnlMenu.add(btnFinanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 80));

        btnSalir.setBackground(new java.awt.Color(2, 62, 138));
        btnSalir.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(232, 230, 230));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoSalir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalir.setIconTextGap(15);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 210, 80));

        btnFinanzas1.setBackground(new java.awt.Color(2, 62, 138));
        btnFinanzas1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnFinanzas1.setForeground(new java.awt.Color(232, 230, 230));
        btnFinanzas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzas.png"))); // NOI18N
        btnFinanzas1.setText("Entregas");
        btnFinanzas1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFinanzas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFinanzas1.setFocusPainted(false);
        btnFinanzas1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanzas1.setIconTextGap(15);
        btnFinanzas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanzas1ActionPerformed(evt);
            }
        });
        pnlMenu.add(btnFinanzas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 210, 80));

        btnFinanzas2.setBackground(new java.awt.Color(2, 62, 138));
        btnFinanzas2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        btnFinanzas2.setForeground(new java.awt.Color(232, 230, 230));
        btnFinanzas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzas.png"))); // NOI18N
        btnFinanzas2.setText("Ventas");
        btnFinanzas2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFinanzas2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFinanzas2.setFocusPainted(false);
        btnFinanzas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanzas2.setIconTextGap(15);
        btnFinanzas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanzas2ActionPerformed(evt);
            }
        });
        pnlMenu.add(btnFinanzas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 210, 80));

        getContentPane().add(pnlMenu);

        pnlPrincipal.setBackground(new java.awt.Color(232, 232, 232));
        pnlPrincipal.setMaximumSize(new java.awt.Dimension(1200, 750));
        pnlPrincipal.setMinimumSize(new java.awt.Dimension(1200, 750));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(1200, 750));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Turno");
        pnlPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 50, -1));

        btnPrepa.setBackground(new java.awt.Color(78, 201, 74));
        btnPrepa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPrepa.setForeground(new java.awt.Color(255, 255, 255));
        btnPrepa.setText("Nuevo Trabajador");
        btnPrepa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPrepa.setFocusPainted(false);
        btnPrepa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrepa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrepaActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnPrepa, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 530, 240, 40));

        jButton4.setBackground(new java.awt.Color(215, 215, 215));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(64, 64, 64));
        jButton4.setText("Herramientas del Gerente");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        pnlPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 390, 33));

        jButton5.setBackground(new java.awt.Color(215, 215, 215));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(64, 64, 64));
        jButton5.setText("Acciones del Perfil");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setBorderPainted(false);
        jButton5.setFocusPainted(false);
        pnlPrincipal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 510, 33));

        btnConsultaAlumnos.setBackground(new java.awt.Color(21, 128, 232));
        btnConsultaAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultaAlumnos.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaAlumnos.setText("Modificar empleados");
        btnConsultaAlumnos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnConsultaAlumnos.setFocusPainted(false);
        btnConsultaAlumnos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultaAlumnos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaAlumnosActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnConsultaAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 630, 240, 40));

        btnModificar.setBackground(new java.awt.Color(102, 16, 173));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar Datos");
        btnModificar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnModificar.setFocusPainted(false);
        btnModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificar.setPreferredSize(new java.awt.Dimension(75, 27));
        btnModificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 240, 40));

        btnPDF.setBackground(new java.awt.Color(2, 62, 138));
        btnPDF.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoPDF.png"))); // NOI18N
        btnPDF.setText("Generar PDF");
        btnPDF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPDF.setBorderPainted(false);
        btnPDF.setFocusPainted(false);
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 160, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bienvenido NOMBRE");
        pnlPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 20, 230, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre");
        pnlPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 100, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 130, 70, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (3).png"))); // NOI18N
        pnlPrincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 130, -1));

        showTurno.setBackground(new java.awt.Color(215, 215, 215));
        showTurno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showTurno.setForeground(new java.awt.Color(102, 102, 102));
        showTurno.setText("Turno");
        showTurno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showTurno.setBorderPainted(false);
        showTurno.setFocusPainted(false);
        showTurno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showTurno.setMargin(new java.awt.Insets(8, 14, 2, 14));
        pnlPrincipal.add(showTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 340, 230, 25));

        jButton7.setBackground(new java.awt.Color(215, 215, 215));
        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jButton7.setForeground(new java.awt.Color(64, 64, 64));
        jButton7.setText("Familia Ferreteria");
        jButton7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton7.setBorderPainted(false);
        jButton7.setFocusPainted(false);
        pnlPrincipal.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 400, 33));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Puesto");
        pnlPrincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 50, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/sol.png"))); // NOI18N
        pnlPrincipal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 30, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Consulta de Empleados, se muestra el nombre");
        pnlPrincipal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 330, -1));

        jButton8.setBackground(new java.awt.Color(215, 215, 215));
        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jButton8.setForeground(new java.awt.Color(64, 64, 64));
        jButton8.setText("Datos del Perfil");
        jButton8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton8.setBorderPainted(false);
        jButton8.setFocusPainted(false);
        pnlPrincipal.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 71, 530, 33));

        showID.setBackground(new java.awt.Color(215, 215, 215));
        showID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showID.setForeground(new java.awt.Color(102, 102, 102));
        showID.setText("Datos del Perfil");
        showID.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showID.setBorderPainted(false);
        showID.setFocusPainted(false);
        showID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showID.setMargin(new java.awt.Insets(8, 14, 2, 14));
        pnlPrincipal.add(showID, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 160, 230, 25));

        showNombre.setBackground(new java.awt.Color(215, 215, 215));
        showNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showNombre.setForeground(new java.awt.Color(102, 102, 102));
        showNombre.setText("Nombre");
        showNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showNombre.setBorderPainted(false);
        showNombre.setFocusPainted(false);
        showNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showNombre.setMargin(new java.awt.Insets(8, 14, 2, 14));
        pnlPrincipal.add(showNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 220, 230, 25));

        showPuesto.setBackground(new java.awt.Color(215, 215, 215));
        showPuesto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        showPuesto.setForeground(new java.awt.Color(102, 102, 102));
        showPuesto.setText("Puesto");
        showPuesto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        showPuesto.setBorderPainted(false);
        showPuesto.setFocusPainted(false);
        showPuesto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        showPuesto.setMargin(new java.awt.Insets(8, 14, 2, 14));
        pnlPrincipal.add(showPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 280, 230, 25));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar (1).png"))); // NOI18N
        pnlPrincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 30, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/id-insignia.png"))); // NOI18N
        pnlPrincipal.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 30, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/maletin.png"))); // NOI18N
        pnlPrincipal.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 30, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/retrato (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 130, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 70, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("ID");
        pnlPrincipal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 20, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 70, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 70, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Consulta de Empleados, se muestra el nombre");
        pnlPrincipal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 330, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 250, 70, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/usuario (2).png"))); // NOI18N
        pnlPrincipal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 250, 70, -1));

        btnBajas1.setBackground(new java.awt.Color(153, 0, 0));
        btnBajas1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBajas1.setForeground(new java.awt.Color(255, 255, 255));
        btnBajas1.setText("Darse de baja");
        btnBajas1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBajas1.setFocusPainted(false);
        btnBajas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBajas1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBajas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBajas1ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnBajas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 260, 40));

        btnConsultaAlumnos1.setBackground(new java.awt.Color(21, 128, 232));
        btnConsultaAlumnos1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultaAlumnos1.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaAlumnos1.setText("Ver todos");
        btnConsultaAlumnos1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnConsultaAlumnos1.setFocusPainted(false);
        btnConsultaAlumnos1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultaAlumnos1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultaAlumnos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaAlumnos1ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnConsultaAlumnos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 400, 190, 30));

        btnConsultaAlumnos2.setBackground(new java.awt.Color(21, 128, 232));
        btnConsultaAlumnos2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConsultaAlumnos2.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaAlumnos2.setText("Dar de baja empleados");
        btnConsultaAlumnos2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnConsultaAlumnos2.setFocusPainted(false);
        btnConsultaAlumnos2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultaAlumnos2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultaAlumnos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaAlumnos2ActionPerformed(evt);
            }
        });
        pnlPrincipal.add(btnConsultaAlumnos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 580, 240, 40));

        getContentPane().add(pnlPrincipal);

        pnlTitulo.setBackground(new java.awt.Color(2, 62, 138));
        pnlTitulo.setMaximumSize(new java.awt.Dimension(1200, 40));
        pnlTitulo.setMinimumSize(new java.awt.Dimension(1200, 40));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(1200, 40));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEscuela.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 18)); // NOI18N
        lblEscuela.setForeground(new java.awt.Color(232, 230, 230));
        lblEscuela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEscuela.setText("INSTITUTO TECNOLÓGICO ASCENCIÓN");
        pnlTitulo.add(lblEscuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 5, -1, 31));

        jLabel5.setForeground(new java.awt.Color(232, 230, 230));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoUsuario.png"))); // NOI18N
        jLabel5.setText("Usuario: Admin");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setMaximumSize(new java.awt.Dimension(125, 30));
        jLabel5.setMinimumSize(new java.awt.Dimension(125, 30));
        jLabel5.setPreferredSize(new java.awt.Dimension(125, 30));
        pnlTitulo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1065, 6, 125, 30));

        getContentPane().add(pnlTitulo);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int salir = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que quieres salir?", "Salir", JOptionPane.YES_OPTION);
        if (salir == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionesActionPerformed
        pnlResultadoBusqueda.cima1 = 0;
        pnlDerecho.removeAll();
        pnlDerecho.add(pnlTitulo);
        pnlDerecho.add(pnlPrincipal);
        pnlNuevaInscripcion.btnOperacion.show();
        revalidate();
        repaint();
        desbloquearEdicion();
    }//GEN-LAST:event_btnInscripcionesActionPerformed
    JPanel pnlFinanzas = new pnlFinanzas();
    private void btnFinanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanzasActionPerformed
        pnlDerecho.removeAll();
        pnlDerecho.add(pnlTitulo);
        pnlDerecho.add(pnlFinanzas);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnFinanzasActionPerformed
    static String operacion;
    static String taller;
    static JPanel pnlInscribir = new pnlNuevaInscripcion();    static pnlResultadoBusqueda pnlBusqueda = new pnlResultadoBusqueda();
    private void btnConsultaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaAlumnosActionPerformed
        pnlResultadoBusqueda.buscarContacto("Mostrar", true, 0);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnConsultaAlumnosActionPerformed
    JPanel pnlGrupos = new pnlGrupos();
    private void btnGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGruposActionPerformed
        pnlDerecho.removeAll();
        pnlDerecho.add(pnlTitulo);
        pnlDerecho.add(pnlGrupos);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnGruposActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        Document documento = new Document(PageSize.A4.rotate());

        JComboBox cbxTablas = new JComboBox();
        cbxTablas.addItem("General");
        cbxTablas.addItem("Primaria");
        cbxTablas.addItem("Secundaria");
        cbxTablas.addItem("Preparatoria");

        Object[] inputFields = {"Seleccione la lista a imprimir:\n", cbxTablas};

        JOptionPane.showConfirmDialog(null, inputFields, "Seleccionar Tabla", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        sql = "SELECT matricula, nombre, apaterno, amaterno, nivel, grado, turno, year, calificacion FROM alumnos";
        switch (cbxTablas.getSelectedItem().toString()) {
            case "General":
                break;
            case "Primaria":
                sql += " WHERE nivel = 'Primaria'";
                break;
            case "Secundaria":
                sql += " WHERE nivel = 'Secundaria'";
                break;
            case "Preparatoria":
                sql += " WHERE nivel = 'Preparatoria'";
                break;
            default:
                break;
        }

        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/Reporte_Inscripciones.pdf"));
            documento.open();
            //Ajustar Fuente
            Font fuente = new Font();
            fuente.setStyle(Font.BOLD);
            fuente.setSize(16);
            //Agregar Titulo
            Paragraph parrafo = new Paragraph("INSTITUTO TECNOLÓGICO ASCENSIÓN", fuente);
            parrafo.setAlignment(Element.ALIGN_CENTER);
            documento.add(parrafo);
            documento.add(Chunk.NEWLINE);
            //Agregar informacion
            documento.add(new Paragraph("Tabla de Alumnos: " + cbxTablas.getSelectedItem().toString()));
            documento.add(new Paragraph("Reporte generado por usuario: Admin\n"));
            documento.add(Chunk.NEWLINE);
            //Crear tabla
            PdfPTable tabla = new PdfPTable(9);
            tabla.setWidthPercentage(100);
            //Ajustar anchura de columnas
            float[] columnWidths = {1.1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f, 1f};
            tabla.setWidths(columnWidths);
            //Ajustar fuente
            fuente = new Font();
            fuente.setStyle(Font.BOLD);
            //Agregar encabezados de tabls
            PdfPCell c1 = new PdfPCell(new Phrase("Matricula", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Nombre", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Ap Paterno", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Ap Materno", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Nivel", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Grado", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Turno", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Año Nac.", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            c1 = new PdfPCell(new Phrase("Calificacion", fuente));
            c1.setHorizontalAlignment(Element.ALIGN_CENTER);
            tabla.addCell(c1);

            try {
                sentencia = reg.createStatement();
                rs = sentencia.executeQuery(sql);

                if (rs.next()) {
                    do {
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        tabla.addCell(rs.getString(6));
                        tabla.addCell(rs.getString(7));
                        tabla.addCell(rs.getString(8));
                        tabla.addCell(rs.getString(9));

                    } while (rs.next());
                    documento.add(tabla);
                }

            } catch (DocumentException | SQLException e) {
            }
            documento.close();

            if (JOptionPane.showConfirmDialog(null, "Reporte guardado en el escritorio\n¿Desea abrirlo?", "Abrir Documento", JOptionPane.YES_OPTION) == 0) {
                try {
                    File path = new File(ruta + "/Desktop/Reporte_Inscripciones.pdf");
                    Desktop.getDesktop().open(path);
                } catch (IOException | java.lang.IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(null, "No se pudo abrir el archivo. Es posible que este haya sido eliminado o movido del escritorio", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (DocumentException | HeadlessException | FileNotFoundException e) {
        }
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnFinanzas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanzas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinanzas1ActionPerformed

    private void btnFinanzas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanzas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinanzas2ActionPerformed

    private void btnPrepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrepaActionPerformed
        operacion = "Preparatoria";
        pnlNuevaInscripcion.llenarGrado();
        pnlDerecho.remove(pnlPrincipal);
        pnlDerecho.add(pnlInscribir);
        revalidate();
        repaint();
        pnlNuevaInscripcion.btnTitulo.setText("Inscripción a Preparatoria");
    }//GEN-LAST:event_btnPrepaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        pnlResultadoBusqueda.buscarContacto("Modificar", true, 0);
        revalidate();
        repaint();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBajas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajas1ActionPerformed

    private void btnConsultaAlumnos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaAlumnos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaAlumnos1ActionPerformed

    private void btnConsultaAlumnos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaAlumnos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaAlumnos2ActionPerformed

    public static void cargarInicio() {
        pnlDerecho.removeAll();
        pnlDerecho.add(pnlTitulo);
        pnlDerecho.add(pnlPrincipal);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Principal().setVisible(true);
            }
        });
    }

    @Override
    public void focusGained(FocusEvent evt) {
        Component c = evt.getComponent();
        if (c == btnInscripciones) {
            btnInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoInscribirActivado.png")));
            btnInscripciones.setBackground(new Color(1, 49, 109));
        } else if (c == btnGrupos) {
            btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoPanelGruposActivado.png")));
            btnGrupos.setBackground(new Color(1, 49, 109));
        } else if (c == btnFinanzas) {
            btnFinanzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzasActivado.png")));
            btnFinanzas.setBackground(new Color(1, 49, 109));
        } else if (c == btnSalir) {
            btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoSalirActivado.png")));
            btnSalir.setBackground(new Color(1, 49, 109));
        }
    }

    @Override
    public void focusLost(FocusEvent evt) {
        Component c = evt.getComponent();
        if (c == btnInscripciones) {
            btnInscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoInscribir.png")));
            btnInscripciones.setBackground(new Color(2, 62, 138));
        } else if (c == btnGrupos) {
            btnGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoPanelGrupos.png")));
            btnGrupos.setBackground(new Color(2, 62, 138));
        } else if (c == btnFinanzas) {
            btnFinanzas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoFinanzas.png")));
            btnFinanzas.setBackground(new Color(2, 62, 138));
        } else if (c == btnSalir) {
            btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IconoSalir.png")));
            btnSalir.setBackground(new Color(2, 62, 138));
        }
    }

    MouseListener ml = new MouseAdapter() {
        @Override
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            Component c = evt.getComponent();
            c.setBackground(new Color(1, 49, 109));
        }

        @Override
        public void mouseExited(java.awt.event.MouseEvent evt) {
            Component c = evt.getComponent();
            if (!c.hasFocus()) {
                c.setBackground(new Color(2, 62, 138));
            }
        }

        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            Component c = evt.getComponent();
            c.setBackground(new Color(1, 49, 109));
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBajas1;
    private javax.swing.JButton btnConsultaAlumnos;
    private javax.swing.JButton btnConsultaAlumnos1;
    private javax.swing.JButton btnConsultaAlumnos2;
    private javax.swing.JButton btnFinanzas;
    private javax.swing.JButton btnFinanzas1;
    private javax.swing.JButton btnFinanzas2;
    private javax.swing.JButton btnGrupos;
    private javax.swing.JButton btnInscripciones;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnPrepa;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblEscuela;
    private javax.swing.JPanel pnlMenu;
    public static javax.swing.JPanel pnlPrincipal;
    public static javax.swing.JPanel pnlTitulo;
    private javax.swing.JButton showID;
    private javax.swing.JButton showNombre;
    private javax.swing.JButton showPuesto;
    private javax.swing.JButton showTurno;
    // End of variables declaration//GEN-END:variables
}
